### ISSUE TITLE
Can't filter search results to Zea mays4m

### ISSUE THREAD

**Issue by mycrobe** [warelab/maizev4-search#10]
Can't filter to Zea mays4m from "All Species" search. It seems that, in Ensembl, the taxon_id is used to look up the name, and so it's set to the v3 "Zea mays".

This came up in #7

**Comment by ajo2995** [comment]
I think it's okay to show zea mays results from each maize assembly/annotation (in this case)

**Comment by mycrobe** [comment]
If you look at [these search results](http://brie:8888/Multi/Search/Results?species=all;idx=;q=GRMZM2G128056;site=ensemblunit), and filter to Zea Mays, you can see that [only the v3 result is kept](http://brie:8888/Multi/Search/Results?species=all;idx=;q=GRMZM2G128056;site=ensemblunit&filter_species=Zea%20mays).

**Comment by mycrobe** [comment]
@ajo2995 but what you describe is probably what _should_ happen.

**Comment by mycrobe** [comment]
Fixed in 1.0.6
