### ISSUE TITLE
Update databases with additional taxon ids for v3 and v4

### ISSUE THREAD

**Issue by mycrobe** [warelab/maizev4-search#13]
Proposed data hack to remove code hacks:
- Create two child taxon nodes underneath maize, one for v3 and one for v4. Suggested taxon ids are `45770003` and `45770004`, with species names `Zea mays v3` and `Zea mays v4`. 
- Modify [the two maps entries](http://devdata.gramene.org/zm4/v50/maps?taxon_id=4577) with the new taxon_ids.
- Change the taxon_ids for all maize genes as appropriate.

This way, the v3 and v4 maize genomes can be visible and searchable in search.gramene.org (or another copy of it—maizev4search.gramene.org?)

**Comment by ajo2995** [comment]
The changes to maps and taxonomy were done by hand. Genes docs were updated by script. This also let us to fix the inconsistent bins (based on taxon_id instead of the system_name hack). The only place where taxon_id was not updated is in the gene trees. This will be dealt with in another issue
